### ISSUE TITLE
Issue with installing - ref

### ISSUE THREAD

**Issue by cococow123** [ChewbaccaCookie/voicemeeter-connector#10]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[X] question about how to use this project

* **Summary**
Hi there! I really like this library and got it working in the past days. However, when I tried to get it functioning with electron, I got some node_module_version errors.

I decided to completely reinstall node to try to fix this. When trying to install this module a second time, I get errors with installing ref.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Node.js version: 12.4.0

npm install ref
```gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN voicemeeter@1.0.0 No description
npm WARN voicemeeter@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

node index.js
```PS C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter> node .\index.js
C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\bindings\bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\build\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\build\Debug\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\build\Release\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\out\Debug\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\Debug\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\out\Release\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\Release\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\build\default\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\compiled\12.13.0\win32\x64\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\addon-build\release\install-root\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\addon-build\debug\install-root\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\addon-build\default\install-root\binding.node
 → C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\lib\binding\node-v72-win32-x64\binding.node
    at bindings (C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ffi\lib\ffi.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:956:30) {
  tries: [
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\build\\binding.node',
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\build\\Debug\\binding.node',
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\build\\Release\\binding.node',
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\out\\Debug\\binding.node',
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\Debug\\binding.node',
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\out\\Release\\binding.node',
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\Release\\binding.node',
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\build\\default\\binding.node',
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\compiled\\12.13.0\\win32\\x64\\binding.node',     
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\addon-build\\release\\install-root\\binding.node',    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\addon-build\\debug\\install-root\\binding.node',  
    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\addon-build\\default\\install-root\\binding.node',    'C:\\Users\\Coco\\Documents\\~Home\\~ Programming\\JS\\voicemeeter\\node_modules\\ref\\lib\\binding\\node-v72-win32-x64\\binding.node'   
  ]
}
```

Hope I can fix this, thanks!

**Comment by cococow123** [comment]
I went back to an older version of node and no longer get these errors.
I would love to get this working with electronjs but it has not been working.

This works fine when using node, but with electron I get this error:
```
App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\build\Release\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\Coco\Documents\~Home\~ Programming\JS\voicemeeter\node_modules\ref\lib\ref.js:5:47)
```

Node version: 10.17.0
Electron version: 3.0.0

**Comment by cococow123** [comment]
Got it working!
